# Generated by Django 4.2.1 on 2023-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
