# Generated by Django 4.2.1 on 2023-05-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_rename_emailid_employee_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
