# Generated by Django 4.2.1 on 2023-05-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
