# Generated by Django 4.2.1 on 2023-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_testimonial_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(upload_to='testimonials'),
        ),
    ]
