# Generated by Django 4.2.1 on 2023-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_alter_testimonial_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='Type',
        ),
    ]
